USE new_personnel;

SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO = 10 ORDER BY COMM;

SELECT ENAME, JOB, SAL FROM EMP ORDER BY JOB ASC, SAL DESC;

SELECT E.DEPTNO, AVG(E.SAL) FROM EMP AS E
JOIN DEPT as D ON E.DEPTNO = D.DEPTNO
GROUP BY E.DEPTNO HAVING COUNT(E.EMPNO) >= 1;

SELECT DEPTNO AS ΤΜΗΜΑ,
ROUND(AVG(TIMESTAMPDIFF(YEAR, HIREDATE, CURDATE())), 1) AS "ΠΡΟΫΠΗΡΕΣΙΑ(έτη)"
FROM EMP GROUP BY DEPTNO;

SELECT P.DESCRIPTION AS PNAME, E.ENAME, E.JOB FROM PROJ AS P
JOIN ASSIGN AS A ON P.PROJ_CODE = A.PROJ_CODE JOIN EMP AS E ON A.EMPNO = E.EMPNO
ORDER BY P.DESCRIPTION, E.JOB;

SELECT D.DNAME AS Department, M.ENAME AS Manager, E.ENAME AS Employee
FROM EMP AS E JOIN EMP AS M ON E.MGR = M.EMPNO JOIN DEPT D  ON M.DEPTNO = D.DEPTNO
ORDER BY D.DNAME, E.ENAME;

SELECT E.ENAME, E.JOB, D.LOC FROM EMP AS E
JOIN DEPT AS D ON E.DEPTNO = D.DEPTNO WHERE D.DNAME = "SALES";

SELECT E.ENAME FROM EMP AS E JOIN ASSIGN AS A ON E.EMPNO = A.EMPNO
JOIN PROJ AS P ON A.PROJ_CODE = P.PROJ_CODE
WHERE P.DESCRIPTION = "PAYROLL" AND A.A_TIME > 50;