USE new_personnel;

SELECT ENAME AS "ΕΠΩΝΥΜΟ", CONCAT(FORMAT(SAL, 0), " €") AS "ΜΙΣΘΟΣ", FORMAT(COMM, 2) AS "ΠΡΟΜΗΘΕΙΑ",
CONCAT(FORMAT(IFNULL((COMM/SAL) * 100, 0), 2), " %") AS "ΠΟΣΟΣΤΟ" FROM EMP;

SELECT ENAME AS "ΕΠΩΝΥΜΟ", CONCAT(FORMAT(SAL, 0), " €") AS "ΜΗΝΙΑΙΕΣ ΑΠΟΔΟΧΕΣ",
CONCAT(FLOOR(DATEDIFF(CURRENT_DATE(), HIREDATE) / 365.25), " έτη") AS "ΠΡΟΫΠΗΡΕΣΙΑ" FROM EMP
WHERE HIREDATE < DATE_SUB(CURRENT_DATE(), INTERVAL 20 YEAR);

SELECT ENAME AS "ΕΠΩΝΥΜΟ", JOB AS "ΘΕΣΗ", HIREDATE AS "ΠΡΟΣΛΗΨΗ" FROM EMP WHERE DAY(HIREDATE) <= 5 AND JOB = "ANALYST" OR JOB = "SALESMAN";

SELECT ENAME AS "ΕΠΩΝΥΜΟ" FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE DEPTNO = 10);

SELECT ENAME AS "ΕΠΩΝΥΜΟ", CONCAT(FORMAT(SAL, 0), " €") AS "ΜΗΝΙΑΙΕΣ ΑΠΟΔΟΧΕΣ" FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT ENAME AS "ΕΠΩΝΥΜΟ", CONCAT(FORMAT(SAL, 0), " €") AS "ΜΗΝΙΑΙΕΣ ΑΠΟΔΟΧΕΣ" FROM EMP
WHERE DEPTNO = 10 AND SAL < (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 20);
